version: '3'

services:
  db:
    image: gyumibear/m2sid-db:latest
    ports:
      - "5432:5432"

  app:
    image: gyumibear/m2sid-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: babacar
      SPRING_DATASOURCE_PASSWORD: babacar
    depends_on:
      - db