name: Pipeline CI/CD de MySurvey

on:
  pull_request:
    branches:
      - main # Déclenché lors d'une Merge Request sur la branche "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configuration d'un runner avec JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Cleaning et installation des dépendances
        run: mvn clean install

      - name: Vérification de la compatibilité entre les plugins
        run: mvn verify

      - name: Lancement des tests
        run: mvn test

      - name: Création des images docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main' }}
          tags: gyumibear/m2sid:latest

      - name: Connexion sur Docker Hub
        if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publication des images Docker
        if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
        run: docker push gyumibear/m2sid:latest