# .github/workflows/ci-cd-dev.yml

name: CI/CD Pipeline for dev Branch

on:
  pull_request:
    branches:
      - dev # Déclenché lors d'une MR sur la branche dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du code
        uses: actions/checkout@v4

      - name: Préparation d'un JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Suppression de l'ancien target et installation des dépendances
        run: mvn clean install

      - name: Vérification de la compatibilité des plugins
        run: mvn verify

      - name: Vérification via des tests
        run: mvn test