name: Spring Boot CI/CD avec un build Docker multi-platform

on:
  push:
    branches:
      - main # Déclenche lorsque du code est poussé sur la branche 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build and Test
        run: mvn clean verify

      - name: Set up QEMU (for cross-platform emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gyumibear/m2sid:latest

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Test with Docker Compose
        run: |
          docker-compose up -d --build
          sleep 30 # Attendre que les services soient prêts
          curl -s http://localhost:8080 || exit 1 # Vérifier que l'application répond
          docker-compose down