name: Spring Boot CI/CD with Docker Build

on:
  push:
    branches:
      - main # Déclenche lorsque du code est poussé sur la branche 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build and Test
        run: mvn clean verify

      - name: SonarQube Scan
        run: mvn sonar:sonar \
          -Dsonar.projectKey=${{ secrets.GIT_TOKEN }} \
          -Dsonar.organization=GyumiBear \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 1 : Construire et pousser l'image de l'application (app)
      - name: Build and Push App Image
        run: |
          docker build -t gyumibear/m2sid-app:latest .
          docker push gyumibear/m2sid-app:latest

      # Étape 2 : Construire et pousser l'image PostgreSQL (db)
      - name: Build and Push DB Image
        run: |
          docker pull postgres:latest
          docker tag postgres:latest gyumibear/m2sid-db:latest
          docker push gyumibear/m2sid-db:latest