# .github/workflows/ci-cd-main.yml

name: CI/CD Pipeline for main Branch

on:
  pull_request:
    branches:
      - main # Déclenché lors d'une MR sur la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Tirer l'image officielle PostgreSQL pour AMD64
      - name: Pull Official PostgreSQL Image for AMD64
        run: docker pull --platform linux/amd64 postgres:latest

      # Retaguer et pousser l'image PostgreSQL pour AMD64
      - name: Retag and Push PostgreSQL Image for AMD64
        run: |
          docker tag postgres:latest gyumibear/postgresql:amd64
          docker push gyumibear/postgresql:amd64

      # Tirer l'image officielle PostgreSQL pour ARM64
      - name: Pull Official PostgreSQL Image for ARM64
        run: docker pull --platform linux/arm64 postgres:latest

      # Retaguer et pousser l'image PostgreSQL pour ARM64
      - name: Retag and Push PostgreSQL Image for ARM64
        run: |
          docker tag postgres:latest gyumibear/postgresql:arm64
          docker push gyumibear/postgresql:arm64

      # Construire et pousser l'image Spring Boot multiplateforme
      - name: Build and Push Spring Boot Application Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gyumibear/m2sid:latest
