# .github/workflows/ci-cd-main.yml

name: CI/CD Pipeline for main Branch

on:
  pull_request:
    branches:
      - main # Déclenché lors d'une MR sur la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Set up QEMU (for cross-platform emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Tirer l'image PostgreSQL officielle
      - name: Pull Official PostgreSQL Image
        run: docker pull postgres:latest

      # Retaguer l'image avec votre nom d'utilisateur
      - name: Retag PostgreSQL Image
        run: docker tag postgres:latest gyumibear/postgresql:latest

      # Pousser l'image retaguée vers votre répertoire DockerHub
      - name: Push PostgreSQL Image to DockerHub
        run: docker push gyumibear/postgresql:latest

      # Construire et pousser l'image Spring Boot
      - name: Build and Push Spring Boot Application Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gyumibear/m2sid:latest
